# Generated by Django 4.1 on 2023-03-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0002_vote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
