# Generated by Django 4.1 on 2023-03-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0005_delete_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="ideas_box",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
