# Generated by Django 4.1 on 2023-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0008_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="ideas_box",
            name="votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
