# Generated by Django 4.1 on 2023-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0010_vote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ideas_box",
            name="votes",
        ),
        migrations.AddField(
            model_name="ideas_box",
            name="downvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ideas_box",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vote",
            name="vote_type",
            field=models.CharField(
                choices=[("upvote", "Upvote"), ("downvote", "Downvote")],
                default="upvote",
                max_length=10,
            ),
        ),
    ]
